apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secco-nginx-https
  namespace: secco
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`secco.nonnoalex.dev`)
      kind: Rule
      services:
        - name: turbine-bot-service
          port: 5000
  tls:
    certResolver: letsencrypt
---
apiVersion: v1
kind: Service
metadata:
  name: turbine-bot-service
  namespace: secco
spec:
  selector:
    app: turbine-bot
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-bot
  namespace: secco
  labels:
    app: turbine-bot
spec:
  selector:
    matchLabels:
      app: turbine-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: turbine-bot
    spec:
      containers:
        - name: turbine-bot
          image: mcanalella/turbine-bot:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
